### ISSUE TITLE
Suggest clarify that `dcm2bids` parts 1 and 2 uses the same BIDS dir

### ISSUE THREAD

**Issue by TrevorKMDay** [DCAN-Labs/data-processing-handbook#109]
Re: https://data-processing-handbook.readthedocs.io/en/latest/nordic/ 

Suggest that it's clarified that you operate on the same BIDS directory both times:

> Load the dcm2bids3 conda environment and run dcm2bids on your dataset with the first config file (everything but phase), then run dcm2bids again with the second config file (to convert phase data and run the NORDIC wrapper via post-op command)

**Comment by audreymhoughton** [comment]
Fixed with @madisoth 's merge
