### ISSUE TITLE
`dcm2bids3` writes to a permanent location on `faird`

### ISSUE THREAD

**Issue by TrevorKMDay** [DCAN-Labs/data-processing-handbook#110]
In debugging `dcm2bids3` with Thomas, he identified that it was writing logs to `/home/faird/shared/code/internal/utilities/Dcm2bids3_NORDIC_wrapper/output_logs/`, which I didn't have write permissions for.

I couldn't get `sbatch -o foo.out -e foo.err` to work (I didn't try very hard) - but it should probably default to writing to `$PWD` or something, not a hardcoded location on MSI.

**Comment by hough129** [comment]
@TrevorKMDay in the s3 section, I believe it mentions changing your output logs path, but we should add a note for the NORDIC section too. 

This is documentation, not a 1:1 codebase where you copy things exactly as is, so please keep that in mind! If you want a wrapper edited, go to the following page to post an issue (this repo is still a work in progress FYI - we are working on cleaning it up): https://github.com/DCAN-Labs/slurm_pipeline_wrappers

**Comment by TrevorKMDay** [comment]
Was the intention that I should have copied and edited `/home/faird/shared/code/internal/utilities/Dcm2bids3_NORDIC_wrapper/nordicsbatch.sh` to run the NORDIC wrapper?

**Comment by hough129** [comment]
I believe so @TrevorKMDay - @madisoth does that sounds right?

**Comment by madisoth** [comment]
Copying the wrapper directory into your project directory isn't required, but is an option if desired.

I updated the MSI version of the wrapper just now to use a relative path ("output_logs" dir) for the logfiles, instead of absolute

**Comment by audreymhoughton** [comment]
@madisoth updated the documentation with the most recent merge
