### ISSUE TITLE
Add release candidate to the software versioning documentation

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/data-processing-handbook#123]
https://www.google.com/search?q=what+does+rc+mean+in+code+versioning&oq=what+does+rc+mean+in+code+versioning&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigAdIBCDY5NzNqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

**Comment by rosemccollum** [comment]
I will fix the formatting for this, something got messed up when I was copying it over from the old rtd I guess

**Comment by rosemccollum** [comment]
Fixed by PR #126
