### ISSUE TITLE
Check first login steps for setting up VPN

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/data-processing-handbook#96]
looks over-complicated and perhaps inaccurate. the documentation provided in the [onboarding doc ](https://docs.google.com/document/d/1Yt6FrblNdhvog02mnlvv_CSsGw67nG4UHFRXNqO5o4Y/edit#heading=h.o51i4ax8i5vh)seems better

**Comment by begim-f** [comment]
The documentation on login steps for setting up VPN has been updated
